cmake_minimum_required(VERSION 3.16)
project(qml6spike LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
find_package(Qt6 REQUIRED COMPONENTS Quick Gui Qml)
find_package(PkgConfig REQUIRED)
pkg_check_modules(GST REQUIRED IMPORTED_TARGET gstreamer-1.0)
qt_add_resources(RES res.qrc)
add_executable(qml6spike main.cpp ${RES})
target_link_libraries(qml6spike PRIVATE Qt6::Quick Qt6::Gui Qt6::Qml PkgConfig::GST)
