[advisories]
version = 2
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

[licenses]
unlicensed = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
